import { SITE_NAME, AUTHOR_PROFILES, HOME_OG_IMAGE_URL } from "./lib/constants";
import type { Metadata } from "next";
import Header from "../components/header";
import Footer from "../components/footer";
import Container from "../components/container";
import HeroUnit from "../components/hero-unit";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./prism.css";

export const metadata: Metadata = {
  title: SITE_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <div className="min-h-screen">
          <main>
            <HeroUnit />
            <Container children={children} />
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
