import { SITE_NAME, AUTHOR_PROFILES, HOME_OG_IMAGE_URL } from "./lib/constants";
import "./globals.css";
import "./prism.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import type { Metadata } from "next";
import Header from "@/components/header";
import LayoutWrapper from "@/components/layout-wrapper";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: SITE_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <LayoutWrapper>{children}</LayoutWrapper>
        <Footer />
      </body>
    </html>
  );
}
